[package]
name = "otp_alpha"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crypto-hash = "0.3.1"